# Site settings
title: Ezeikel Pemberton - Web Developer
email: ezeikelpemberton@gmail.com
description: The best Web Developer in the world!
url: "http://ezeikel.co.uk" # the base hostname & protocol for your site
twitter_username: ezeikel_
github_username:  ezeikel_
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Ezeikel Pemberton
      layout: "post"
      category: web
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
