# Site settings
title: Ezeikel Pemberton - Front End Developer.
email: ezeikelpemberton@gmail.com
description: Front End Developer based in London. Available for contract. Experience working in Digital Agencies for big brand clients.
url: "http://ezeikel.co.uk" # the base hostname & protocol for your site
twitter_username: ezeikel_
github_username:  ezeikel_
#paginate: 5

# Build settings
markdown: kramdown
permalink: /:title
excerpt_separator: <!--more-->
plugins:
  #- jekyll-paginate
  #- jekyll-mentions
  #- jemoji
  #- jekyll-redirect-from
  #- jekyll-sitemap
  #- jekyll-feed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Ezeikel Pemberton
      layout: "post"
      category: "front end"
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
